### ISSUE TITLE
Containers still vanishing

### ISSUE THREAD

**Issue by ValkyrX** [ScreepsGamers/screeps.behaviour-action-pattern#134] opened 2016-09-10 08:45 UTC
The issue with containers vanishing continues, i think the issue is this, the creeps are not repairing them so it is solely down to the towers, however when your controller level goes up it dedicates all its repair energy on roads and walls and ignores the containers as if they are a lower priority.

**Comment by cyberblast** [comment] 2016-09-10 14:15
But the workers should repair them as well. At least when it's getting "urgent". 
Repair priority goes by hits. That is those with lowest hits get it first. No matter which structureType. 

We increased that "urgent" threshold for containers with the last commit (to 15k hits by default). To handle the dramatic decay rate of containers.  That means, workers should start repairing a container when its hits get below 15k. Above 15k its only a tower job. 
In both cases, its always the structure with the lowest hits value thats taken care of... 
Did you already try that latest version?

**Comment by ValkyrX** [comment] 2016-09-10 15:43
Hi, yes i have tried the latest version and its still the same outcome, everything is stable until my controller levels up, then all the walls go form say 10k hits to 20k so my tower just sits there repairing all the walls, i have watched the creeps for hours so far and have yet to see them repairing anything..

**Comment by BringerOD** [comment] 2016-09-10 15:48
Maybe we can sort the repairables by a priority.  Containers being the top of the list?

The latest fixes have work for me and I just upgraded my controller.  This does not mean you are not having an issue.

**Comment by ValkyrX** [comment] 2016-09-10 16:17
nope its the same as the repo, set at 1000 , it owuld be good if we could figure a way to prioritize containers as if they vanish basically unless dropmining is on the whole room goes a bit crazy until you can build a new conatiner. I have ensured my code is as is in the repo, only diference is on the haulers i have set fueling to the top so they keep the towers filled, this way at least the towers can keep up with the decay rate of the containers.

**Comment by cyberblast** [comment] 2016-09-13 14:55
I can't reproduce the issue. In the meanwhile I claimed a new room and everything is running smoothly, also in lower room levels (1-4). 
@ValkyrX : Are you still experiencing the issue? 
Whats your room name?

**Comment by Animatrixy** [comment] 2016-09-13 21:06
Nope the issue seems solved at the minute on my end also

**Comment by cyberblast** [comment] 2016-09-13 21:55
Ok, I'll optimistcal close this one. 
Please report back if this is ocurring still/again...

**Closed by cyberblast** 2016-09-13 21:55 UTC
Labels: bug
