### ISSUE TITLE
Claimer not spawning

### ISSUE THREAD

**Issue by ValkyrX** [ScreepsGamers/screeps.behaviour-action-pattern#230] opened 2016-10-23 09:20 UTC
Hi guys, using recent code , so i have set a claim flag (white.white) in another room and so far its been 2 days and no claimers have spawned, i have enough resources in any of my 4 rooms, nothing else is in the spawn q however no claimer is setup, i notices in setup.claimer that there is no mention of claim flag ? what procedure is now needed to make a claim ? i have also tried reserve and still nada, everything else spawns fine ?

Thanks

**Comment by Dasku** [comment] 2016-10-23 09:36
I'd suggest using the master branch code at the moment as I think the dev code is in the middle of an update, I had an error when I tried it and another guy also posted saying he was getting an error.

**Comment by Dasku** [comment] 2016-10-23 09:37
Looks like it was updated 4 hours ago, going to try it again now.

**Comment by ValkyrX** [comment] 2016-10-23 11:26
I have tried the new code, so i dont get the errors regarding missing script which is cool, but for the life of me no matter where i put a claim flag no claimers are spawned at all...

**Comment by Dasku** [comment] 2016-10-24 16:49
Sorry thought I'd replied to this. What level is your controller and global level?

**Comment by ValkyrX** [comment] 2016-10-24 21:41
Hey there thanks for reply, so I gave various controllers ranging from rcl 5 and 6

**Comment by SirLovi** [comment] 2016-10-24 22:02
1. You need energy for claimer to spawn
2. It depends on the distance of the flag from the spawn (claimerMaxWeight has variable *range* which is set to 2 by default due to claimers having short life

I bypass this, when I need to claim something farther but still accessible, by placing a claim flag where I need it.. and another one in the room with a spawn... After the spawn starts spawning a claimer I delete the flag in that room and once the claimer is spawned, he'll go and claim the room with the remaining flag.

**Comment by ValkyrX** [comment] 2016-10-25 18:18
Hmm interesting I will try that and see if it works, thanks a lot will advise

**Comment by ValkyrX** [comment] 2016-10-25 19:41
Hi there, nope been waiting for a day now with a claim flag in the room itself where the spawner is and it will not spawn a claimer at all, nor if i put the claim flag in the next unclaimed room

**Comment by Dasku** [comment] 2016-10-25 19:42
This is really odd because I have claimed a room in the last 24 hours with the same code as you have. I use White/Green so it builds a controller where I want it and a White/Red to send an extra pioneer.

**Comment by ValkyrX** [comment] 2016-10-25 19:44
Hmm I use white/white wonder if that’s the difference, I will try a white green to see if that works

**Comment by ValkyrX** [comment] 2016-10-25 20:11
So i tried white/greem , i get the pioneer spawn and goto the room but because i havent claimed it they sit idle when they arrive

**Comment by Dasku** [comment] 2016-10-25 20:17
Do you have a white flag in there also?

**Comment by SirLovi** [comment] 2016-10-25 20:18
Tell me your room name or username.. This is weird..
Make sure to delete your scripts and freshly upload latest one.

**Comment by ValkyrX** [comment] 2016-10-25 21:56
Hi mate my name is Animatrix in game

**Comment by cyberblast** [comment] 2016-10-26 13:51
Hi, 
sorry for the delay. 
SirLovi is right, the issue is probably due to the distance of the room you are trying to claim. 
You can also increase that value. 
* In room.js at claimerMaxWeight property there is a let maxRange = 2; variable. Increase that to allow spawning of claimers for flags far away.
* in FlagDir.js at claimMod function you can find the logic the claimer will use to find the next "nearest" room. room range has been multiplied with 50 before. Rooms with distance >2 get a *3 penalty. and >4 get their range set to Infinity... 

This whole procedure may sometime get replaced by a "task based approach", as also described in #196. E.g. "there is a task to claim a room" => "check best spawn to build claimer" => "add creeptype to spawn queue" => "spawning creep gets same task" => etc.

**Comment by ValkyrX** [comment] 2016-10-26 15:40
Hi I have tried in a room right next to one I already occupy so dunno what the issue is

Thanks

**Comment by ValkyrX** [comment] 2016-10-26 15:41
I have now tried uping the maxweight to 10 and still no claimer spawns, the room is right next to one of my lvl 6 spawn rooms.. ?

**Comment by cyberblast** [comment] 2016-10-26 18:07
> the room is right next to one of my lvl 6 spawn rooms  

Thats really strange. Could you please try calling `Game.spawns['YourSpawnName'].createCreepBySetup(Creep.setup.claimer)` for a spawn that has at least 60% energy available (spawns+extensions)? 
Will it create that creep?

**Comment by ValkyrX** [comment] 2016-10-26 21:05
tried that it says null im afraid ..

**Comment by cyberblast** [comment] 2016-10-27 05:53
And no claimer spawned I guess.. ok :/ 
And when calling 
`Creep.setup.claimer.isValidSetup(Game.rooms['YourRoomName'])` 
for a room that should be valid (extensions filled and not too far from flag)?

**Comment by ValkyrX** [comment] 2016-10-27 06:53
Ok when calling Creep.setup.claimer.isValidSetup(Game.rooms['YourRoomName']) it says true, and Game.rooms['YourRoomName'].conserveForDefense returns false, however Game.spawns['YourSpawnName'].createCreepBySetup(Creep.setup.claimer) returns null ?

**Comment by ValkyrX** [comment] 2016-10-27 06:57
This is all clean code , i have changed nothing in it at all

**Comment by ValkyrX** [comment] 2016-10-27 07:07
sorry clicked close and not commenbt lol

**Comment by cyberblast** [comment] 2016-10-27 09:34
When it returns null, is there anything else logged to the console? 
Please also ensure you have parameters DEBUG & CENSUS_ANNOUNCEMENTS set to true...

**Comment by ValkyrX** [comment] 2016-10-27 15:38
No nothing else is logged at all, just null

Regards
K

[Description: PA Email Banner]
[Description: parallelbanner]<https://u2208687.ct.sendgrid.net/wf/click?upn=5XngVQO2iDp-2FKXnR0Fg8i0Ibp7hZXPK6SdCHf-2BRclYnJ13hpp5SBUEDgJaz8dqLy_FynH2tOgOcVvzSA627n2z5sIswhw8k4yqJj6fLeAiMhyFJgn7Z2SmGE1uvIhYx7h39v4-2FovwjiY0L7rBN2m-2FOaXd0YB4D-2B3Yj9BqrcLJ0BPBHneMh19PE39GM6JJ-2FgkI1-2F32uLlbfmdFdZR4rK1rXkfqXyLq9MA9lYMChp-2FiQ0c65065f4Gu6teIfBviqt8hVljHWKwTF66D-2Bc4pi9w2p1o4q9LeUq-2FfLWpcw9Md-2FZA-3D>

 Privacy & Confidentiality Notice
This e-mail is confidential and may be privileged, and the information contained with it intended only for the named recipient, firm or company to whom it is addressed. If you are not the intended recipient, please notify the sender immediately - do not copy this email, nor disclose the contents to any other person or use it for any purpose.
Computer viruses can be transmitted by email. You should check this email and any attachments for the presence of viruses. We accept no liability for any damage caused by any virus transmitted by this email or any attachments.

**Comment by ValkyrX** [comment] 2016-10-27 15:43
Hi so i tried calling the creep it just return null in the console, no matter which spawn I try

**Comment by cyberblast** [comment] 2016-10-27 17:17
Don't know if it (6476391) really helps, but could maybe solve the problem...

**Comment by ValkyrX** [comment] 2016-10-27 18:46
Yup thats fixed it, as soon as i loaded the new code a claimer was spawned and he is merily on his way to claim now, will update if all goes well soon, thanks

**Comment by cyberblast** [comment] 2016-10-27 19:10
Phew, that was a hard nut :)

**Comment by ValkyrX** [comment] 2016-10-27 20:15
yup thanks all for the help, he has claimed and now pioneers are on the way to build so i think we can "claim" lol this is closed,thanks a lot

**Comment by cyberblast** [comment] 2016-10-27 20:23
Glad to hear its working now. And this gap has been closed! 
Thx for all supporting in this case. 
Closing...

**Closed by cyberblast** 2016-10-27 20:23 UTC
Labels: bug, question
