### ISSUE TITLE
idle condition

### ISSUE THREAD

**Issue by Gestic** [ScreepsGamers/screeps.behaviour-action-pattern#217] opened 2016-10-14 05:23 UTC
So my second room got RC6, the first one was running fine RC6 as well. Plunked down 10 more extensions. (room had max extensions previously plus 2 towers, and 2 containers per node. no other structures) At this point everything was smooth as usual, had 2 miners (1 per node), 2 haulers and 2 workers. I came back about an hour later and all extensions were built except for 4 and all extensions were empty. There was only 1 worker and 1 hauler left which were idle.

I destroyed 2 of the containers one after the other which got the worker and the hauler out of idle. I also had to destroy the two towers i had since all they were doing was using the dropped resources on the towers to update all the structures. Once i did that they finally started to refill the extensions which then spawned low level workers which are now starting the whole process back up.  

As i write this, the base just spawned miners again. Whew.

**Comment by Gestic** [comment] 2016-10-14 05:28
btw this whole time my first room was running smoothly including a privateers which were mining a red/green flag room as well as spawning claimers since it is flagged white as well waiting for my GCL3.

**Comment by cyberblast** [comment] 2016-10-14 07:02
Thats strange :/ 

Haulers first priority is always "feeding" of extensions. 

Question is why there were no more miners. 

I will try some tuning around this, but cant guarantee as this is hard to reproduce/test...

**Comment by cyberblast** [comment] 2016-10-14 07:06
Tuning: 
* prefer spawning of miners above workers
* Allow worker harvesting when there is no miner (or no hauler)
* Workers prefer feeding, when there is no miner (or no hauler)

**Comment by SirLovi** [comment] 2016-10-14 07:15
> Allow worker harvesting when there is no miner (or no hauler)
> Workers prefer feeding when there is no miner (or no hauler)

I second this.. It allows to build containers even before miners are spawned

**Comment by cyberblast** [comment] 2016-10-14 07:18
Yes, but that was also possible before. Both sentences were true before, only with the hauler condition. And hauler will not spawn without miner ;) 

Its only a corner case taken care of...

**Comment by Gestic** [comment] 2016-10-14 11:44
may have been the case that i was attacked when i was gone.. but i saw no messages of such. didnt look in memory though. just got wiped moments ago. seems he was attacking with tough healers to see reactions..

**Comment by cyberblast** [comment] 2016-10-14 12:56
Did you try out if the new changes are helpful? At least with the miner problem? (before the wipe)

**Comment by Gestic** [comment] 2016-10-16 06:45
didnt have time to update, was attacked shortly after. respawning now

**Comment by cyberblast** [comment] 2016-10-16 06:53
Ok. I will close this one and cross my fingers it's working better now.
May be reopened if it's happening again.

**Comment by Gestic** [comment] 2016-10-21 07:40
So now I have 3 bases, this has happened again 3 times and it's very easy to reproduce. The problem is that workers or haulers (at RC4) will not fill extensions so that the energy does not meet min for spawning miners (or anything else) if you have something that's being built. Happens esp. if building storage or a few extenders or many base structures.

**Comment by cyberblast** [comment] 2016-10-21 07:44
But they should fill extensions. Its the first priority of the hauler! Also first priority of the worker if there is not at least one hauler and one miner...

**Comment by Gestic** [comment] 2016-10-21 07:45
I can video capture it for you if you wish.. even updated the script yesterday i believe

**Comment by cyberblast** [comment] 2016-10-21 07:47
do you have a storage in that room? Which room is it?

**Comment by Gestic** [comment] 2016-10-21 07:49
no i am building storage

**Comment by Gestic** [comment] 2016-10-21 07:51
i dont know what to do.. i may have to destroy my turret for energy so that the hauler will  pick it up like last time

**Comment by cyberblast** [comment] 2016-10-21 07:52
Which room is it? I don't know why this is happening to you, as this is not happening to anybody else. May I have a look into your room... ?

**Comment by Gestic** [comment] 2016-10-21 07:53
W69S54 look for Noxeth its my very Westerly room

**Comment by Gestic** [comment] 2016-10-21 07:57
it may be because the container's energy for each resource point was pretty low

**Comment by cyberblast** [comment] 2016-10-21 08:00
looks everything ok..., not? 
Container need a certain level before they get emptied. 
I'd also advice to use less containers. only 1 per source. as containers are quite expensive to keep up (decay)
this will save A LOT!
and its not required to have more than 1
I also believe this is the main problem. It makes your economy instable

**Comment by cyberblast** [comment] 2016-10-21 08:01
You should also use less roads. same reason...

**Comment by cyberblast** [comment] 2016-10-21 08:06
All your energy goes into structures. It should go into your controller instead ;)

**Comment by Gestic** [comment] 2016-10-21 08:08
but you see what i mean? the workers keep on building instead of filling extenders or letting haulers fill them

**Comment by Gestic** [comment] 2016-10-21 08:08
lots of my energy goes into building creeps for attacking/defense

**Comment by cyberblast** [comment] 2016-10-21 08:11
Yes, it's the workers job to do that once there are haulers. Thats ok. Problem is there is no more energy left for the haulers. Thats because there is too much energy loss (see reasons above)
The most important thing in low level RCL (< 6) is to get the economy running and to get a higher RCL.  
Once you have a storage and some energy buffer things are more relaxed

**Comment by Gestic** [comment] 2016-10-21 08:14
ok ill take your advice

**Comment by cyberblast** [comment] 2016-10-21 08:19
I'd also rethink about all those ramparts and if they are required. If you need a better wall you should increase its hit points first instead of building a second row wall or a rampart on top of it. 
You can also adjust the level up to what walls get build by adjusting parameters -> MAX_REPAIR_LIMIT
Ramparts will decay and are causing permanent costs

**Comment by SirLovi** [comment] 2016-10-21 09:40
Ramparts are the worst enemy of RCL praising..
They take too much energy to maintain.. Fewer the ramparts, the better.. Walls are not worse than ramparts..

**Closed** 2016-10-26 19:01 UTC
Labels: bug, Code ready for validation
